# Generated by Django 5.1.6 on 2025-03-07 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_user_notification_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='date_taken',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='feedback',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(),
        ),
    ]
